export const CREATE_ROOM_REQUEST = "CREATE_ROOM_REQUEST";
export const CREATE_ROOM_SUCCESS = "CREATE_ROOM_SUCCESS";
export const CREATE_ROOM_FAIL = "CREATE_ROOM_FAIL";

export const GET_ALL_ROOM_REQUEST = "GET_ALL_ROOM_REQUEST";
export const GET_ALL_ROOM_SUCCESS = "GET_ALL_ROOM_SUCCESS";
export const GET_ALL_ROOM_FAIL = "GET_ALL_ROOM_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
